project:
  type: book
  output-dir: docs

book:
  title: "Style Guide, Editorial, & Publishing Manual"
  subtitle: "Citizen Science for Research Libraries Guide"
  author: # repeat as often as needed
   - name: "Simon Worthington"
     orcid: 0000-0002-8579-9717
     email: simon.worthington@tib.eu
     affiliations:
      - name: TIB - Leibniz Information Centre for Science and Technology and University Library
   - name: "Stefan Wiederkehr"
  date: "11/7/2024"
  chapters:
    - index.qmd
    - style-manual.qmd
    - editorial-manual.qmd
    - publishing-manual.qmd
  repo-url: hhttps://github.com/cs4rl/style-editorial-publishing-manual
  repo-actions: [edit]
  downloads: [pdf,docx]

# Quarto allows commenting using either Hypothesis or Utterances
# https://quarto.org/docs/reference/projects/books.html#comments
comments:
  hypothesis: true

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  docx: 
    toc: true  



